version: "3"
services:
  php:
    build:
      context: .
    container_name: php-cep
    volumes:
      - ".:/app"
    ports:
      - 8383:80
      - 8000:8000
    networks:
      - default
    depends_on:
      - mysql
    entrypoint: ["php", "bin/console", "server:run", "0.0.0.0:80"]

  mysql:
    image: mysql:5.7
    container_name: db
    ports:
      - 3309:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=viacep"
      - "MYSQL_DATABASE=viacep"
    volumes:
      - "./infra/mysql:/var/lib/mysql"
    networks:
      - default

networks:
  default:
    driver: bridge