version: "3"
services:
  php:
    build:
      context: .
    container_name: php-cep
    volumes:
      - ".:/app"
    ports:
      - 8383:80
    networks:
      - default
    depends_on:
      - mysql
      - redis
    environment:
      - APP_ENV=dev
    entrypoint: ["sh", "build.sh"]

  mysql:
    image: mysql:5.7
    container_name: db
    ports:
      - 3309:3306
    environment:
      - "MYSQL_ROOT_PASSWORD=viacep"
      - "MYSQL_DATABASE=viacep"
    volumes:
      - "./infra/mysql:/var/lib/mysql"
    networks:
      - default
    command: mysqld --sql_mode="" --general_log=1 --general_log_file=/var/log/mysql/mysql.log

  redis:
    image: redis
    container_name: cache

networks:
  default:
    driver: bridge