version: "3"
services:
  php:
    build:
      context: .
    container_name: php-cep
    volumes:
      - ".:/app"
    ports:
      - 8383:80
    networks:
      - dojo-docker-ex5
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: db
    ports:
      - 3309:3306
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=viacep"
    volumes:
      - "./infra/mysql:/var/lib/mysql"
    networks:
      - dojo-docker-ex5

networks:
  dojo-docker-ex5:
    driver: bridge